import "./globals.css";
import { ThemeProvider as NextThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import CoreUI from "@/components/custom/dashboard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen font-mono antialiased overflow-x-hidden">
        <ClerkProvider>
          <NextThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            {children}
          </NextThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
