import "./globals.css";
import { ThemeProvider as NextThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-mono antialiased`}>
        <ClerkProvider>
          <NextThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            {children}
          </NextThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
